global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'arthurbernard.dev@gmail.com'
  smtp_auth_username: 'arthurbernard.dev@gmail.com'
  smtp_auth_password: 'khyw ymab tugm fsss'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'service', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 5m
  receiver: 'email-admin'

receivers:
  - name: 'email-admin'
    email_configs:
      - to: 'arthurbernard.dev@gmail.com'
        headers: { Subject: '{{ template "email.subject" . }}' }
        html: '{{ template "email.body" . }}'

templates:
  - '/etc/alertmanager/email.tmpl'
